baseURL = 'https://stym06.github.io/'
languageCode = 'en-us'
title = 'Blog by Satyam'
theme = 'PaperMod'
enableEmoji=true

[params.homeInfoParams]
Title = "Hi there :wave:"
Content = "Welcome to my little corner on the internet :tokyo_tower:"

[[params.socialIcons]]
name = "LinkedIn"
url = "https://linkedin.com/in/stym06"

[[params.socialIcons]]
name = "X"
url = "https://x.com/stym06"